; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only
#define MyAppName "HPR"
#define MyAppVersion "v0.9.11"
#define MyAppPublisher "Plexescor"
#define MyAppURL "github.com/plexescor/HPR"
#define MyAppExeName "HPR.exe"

[Setup]
AppId={{5A5C9793-0BDC-4E75-A376-FB7112138859}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputDir=C:\HPR\INNO\v0.9.11
OutputBaseFilename=HPRv0.9.11
SetupIconFile=C:\HPR\v0.9.11\assets\icon.ico
SolidCompression=yes
WizardStyle=modern dark windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone
Name: "startupicon"; Description: "Start HPR automatically at Windows startup"; GroupDescription: "Startup:"; Flags: checkablealone

[Files]
; -- App binaries --
Source: "C:\HPR\v0.9.11\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\HPR\v0.9.11\slint_cpp.dll"; DestDir: "{app}"; Flags: ignoreversion

; -- aliases.csv and config.csv: Pascal handles overwrite logic --
Source: "C:\HPR\v0.9.11\aliases.csv"; DestDir: "{userappdata}\HPR\HPR_Config"; Flags: ignoreversion; Check: ShouldCopyAliases
Source: "C:\HPR\v0.9.11\tabAliases.csv"; DestDir: "{userappdata}\HPR\HPR_Config"; Flags: ignoreversion; Check: ShouldCopyTabAliases
Source: "C:\HPR\v0.9.11\config.csv"; DestDir: "{userappdata}\HPR\HPR_Config"; Flags: ignoreversion; Check: ShouldCopyConfig
Source: "C:\HPR\v0.9.11\projectAliases.csv"; DestDir: "{userappdata}\HPR\HPR_Config"; Flags: ignoreversion; Check: ShouldCopyProjectAliases

; -- assets: always silently overwrite --
Source: "C:\HPR\v0.9.11\assets\*"; DestDir: "{userappdata}\HPR\HPR_Config\assets"; Flags: ignoreversion recursesubdirs createallsubdirs

; -- ui-REFERENCEONLY: always silently overwrite --
Source: "C:\HPR\v0.9.11\ui\*"; DestDir: "{userappdata}\HPR\HPR_Config\ui-REFERENCEONLY"; Flags: ignoreversion recursesubdirs createallsubdirs

; -- ui: always silently overwrite
Source: "C:\HPR\v0.9.11\ui\*"; DestDir: "{userappdata}\HPR\HPR_Config\ui"; Flags: ignoreversion recursesubdirs createallsubdirs

[Dirs]
Name: "{userappdata}\HPR\HPR_Config"


[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "HPR"; ValueData: "{app}\{#MyAppExeName}"; Tasks: startupicon; Flags: uninsdeletevalue

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]

var
  AliasOverwriteConfirmed: Boolean;
  TabAliasOverwriteConfirmed: Boolean;
  ProjectAliasOverwriteConfirmed: Boolean;
  ConfigOverwriteConfirmed: Boolean;

function ShouldCopyAliases(): Boolean;
begin
  Result := (not FileExists(ExpandConstant('{userappdata}\HPR\HPR_Config\aliases.csv')))
            or AliasOverwriteConfirmed;
end;

function ShouldCopyTabAliases(): Boolean;
begin
  Result := (not FileExists(ExpandConstant('{userappdata}\HPR\HPR_Config\tabAliases.csv')))
            or TabAliasOverwriteConfirmed;
end;

function ShouldCopyProjectAliases(): Boolean;
begin
  Result := (not FileExists(ExpandConstant('{userappdata}\HPR\HPR_Config\projectAliases.csv')))
            or ProjectAliasOverwriteConfirmed;
end;

function ShouldCopyConfig(): Boolean;
begin
  Result := (not FileExists(ExpandConstant('{userappdata}\HPR\HPR_Config\config.csv')))
            or ConfigOverwriteConfirmed;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ConfigDir: String;
  Res: Integer;
begin
  Result := True;

  if CurPageID = wpReady then
  begin
    ConfigDir := ExpandConstant('{userappdata}\HPR\HPR_Config');

    // aliases.csv
    if FileExists(ConfigDir + '\aliases.csv') then
    begin
      Res := MsgBox(
        'aliases.csv already exists.' + #13#10 +
        'Overwrite it? Your custom edits will be lost.',
        mbConfirmation, MB_YESNO
      );
      AliasOverwriteConfirmed := (Res = IDYES);
    end;
    
    // tabAliases.csv
    if FileExists(ConfigDir + '\tabAliases.csv') then
    begin
      Res := MsgBox(
        'tabAliases.csv already exists.' + #13#10 +
        'Overwrite it? Your custom edits will be lost.',
        mbConfirmation, MB_YESNO
      );
      TabAliasOverwriteConfirmed := (Res = IDYES);
    end;

    // projectAliases.csv
    if FileExists(ConfigDir + '\projectAliases.csv') then
    begin
      Res := MsgBox(
        'projectAliases.csv already exists.' + #13#10 +
        'Overwrite it? Your custom edits will be lost.',
        mbConfirmation, MB_YESNO
      );
      ProjectAliasOverwriteConfirmed := (Res = IDYES);
    end;

    // config.csv
    if FileExists(ConfigDir + '\config.csv') then
    begin
      Res := MsgBox(
        'config.csv already exists.' + #13#10 +
        'Overwrite it? Your custom edits will be lost.',
        mbConfirmation, MB_YESNO
      );
      ConfigOverwriteConfirmed := (Res = IDYES);
    end;
  end;
end;
